# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-27 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(db_index=True, max_length=20, verbose_name='车站名称')),
                ('station_code', models.CharField(db_index=True, max_length=20, verbose_name='车站名称')),
            ],
        ),
    ]
