# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-22 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15, verbose_name='用户姓名')),
                ('upwd', models.CharField(max_length=15, verbose_name='用户密码')),
                ('phone', models.IntegerField(verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
    ]
