# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-22 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190622_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='email',
            new_name='uemail',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='phone',
            new_name='uphone',
        ),
    ]
