# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitudes', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('latitudes', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='纬度')),
            ],
        ),
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sce_details', models.TextField(verbose_name='景区介绍')),
            ],
        ),
        migrations.CreateModel(
            name='Scenic1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sce_name', models.CharField(max_length=8, verbose_name='景点名称')),
                ('sce_topic', models.CharField(max_length=15, verbose_name='主题名称')),
                ('brief_des', models.CharField(max_length=32, verbose_name='景点简述')),
                ('bus_go', models.CharField(max_length=25, verbose_name='公交')),
                ('car_go', models.CharField(max_length=25, verbose_name='自驾')),
                ('pre_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='原价')),
                ('local_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='现价')),
                ('rebate', models.FloatField()),
                ('low_time', models.DateField(default='2019-9-20', verbose_name='优惠截止时间')),
                ('grage', models.CharField(default='AAAA', max_length=10, verbose_name='景区级别')),
                ('sce_address', models.CharField(max_length=15, verbose_name='景区地址')),
                ('open_time', models.CharField(max_length=65, verbose_name='景区地址')),
                ('img_1', models.ImageField(upload_to='', verbose_name='景点图片1')),
                ('img_2', models.ImageField(upload_to='', verbose_name='景点图片2')),
                ('img_3', models.ImageField(upload_to='', verbose_name='景点图片3')),
                ('img_4', models.ImageField(upload_to='', verbose_name='景点图片4')),
                ('img_5', models.ImageField(upload_to='', verbose_name='景点图片5')),
                ('word1', models.CharField(max_length=5, null=True, verbose_name='主题词1')),
                ('word2', models.CharField(max_length=5, null=True, verbose_name='主题词1')),
                ('word3', models.CharField(max_length=5, null=True, verbose_name='主题词1')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=5, verbose_name='门票种类')),
                ('ticket_name', models.CharField(max_length=15, verbose_name='门票名称')),
                ('play_time', models.DateField(verbose_name='游玩时间')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='门票价格')),
                ('ticket_num', models.IntegerField(default=1, verbose_name='预定数量')),
                ('sumprice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='金额')),
                ('sce_name3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.Scenic1')),
            ],
        ),
        migrations.AddField(
            model_name='introduce',
            name='sce_name2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scenic.Scenic1'),
        ),
        migrations.AddField(
            model_name='address',
            name='sce_name2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scenic.Scenic1'),
        ),
    ]
