# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0002_auto_20190625_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenic1',
            name='rebate',
            field=models.FloatField(null=True, verbose_name='折扣率'),
        ),
    ]
