# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0004_auto_20190626_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenic1',
            name='open_time',
            field=models.CharField(max_length=80, verbose_name='开放时间'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_name',
            field=models.CharField(max_length=20, verbose_name='门票名称'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(max_length=10, verbose_name='门票种类'),
        ),
    ]
