# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=20, verbose_name='酒店名字')),
                ('address', models.CharField(max_length=100, verbose_name='酒店地址')),
                ('phone', models.CharField(max_length=20, verbose_name='酒店电话')),
                ('info', models.TextField(verbose_name='酒店详细信息')),
                ('hotel_p11', models.ImageField(upload_to='', verbose_name='酒店图片1')),
                ('hotel_p12', models.ImageField(upload_to='', verbose_name='酒店图片2')),
                ('hotel_p13', models.ImageField(upload_to='', verbose_name='酒店图片3')),
                ('hotel_p14', models.ImageField(upload_to='', verbose_name='酒店图片4')),
                ('hotel_p15', models.ImageField(upload_to='', verbose_name='酒店图片5')),
                ('hotel_level', models.CharField(max_length=10, verbose_name='酒店级别')),
            ],
        ),
    ]
