# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-25 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_p11',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_p12',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_p13',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_p14',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_p15',
        ),
    ]
