# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-25 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20190625_1306'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='hotel',
        ),
    ]
