# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-25 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20190625_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='酒店电话'),
        ),
    ]
