# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-26 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20190626_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_count',
            field=models.IntegerField(default=30, verbose_name='剩余房间数量'),
        ),
    ]
