# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-26 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20190626_2019'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='house',
            table='house',
        ),
    ]
